// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;
using UnityEngine.Networking;

public class RunningSceneGUI : MonoBehaviour {
	
	NetworkManager nm;
	public Text teamAScore;
	public Text teamBScore;
	
	public void Start(){
		nm = NetworkManager.singleton;
		nm.client.RegisterHandler (Msgs.clientTeamScore, OnClientReceiveTeamList);
	}
	
	public void AddScore(int team, int score){
		AddScore sc = new AddScore();
		sc.team = (int) team;
		sc.score = (int)score;
		nm.client.Send(Msgs.clientTeamScore, sc);
	}
	
}

